package org.traccar.forward.sutran;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.traccar.config.Config;
import org.traccar.forward.PositionData;
import org.traccar.model.Device;
import org.traccar.model.ForwardDelivery;
import org.traccar.model.ForwardServer;
import org.traccar.model.Position;
import org.traccar.storage.DatabaseStorage;
import org.traccar.storage.StorageException;
import org.traccar.storage.query.Columns;
import org.traccar.storage.query.Request;

import java.time.Instant;
import java.util.Date;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.*;

class SutranRecoveryStorageTest {

    private static class Fixture implements AutoCloseable {
        final ObjectMapper mapper = new ObjectMapper();
        final java.sql.Connection connection;
        final DatabaseStorage storage;
        final ForwardServer server = new ForwardServer();
        String failingStatus;
        boolean failingRecoveryRead;
        boolean failingAttemptWrite;

        Fixture() throws Exception {
            var source = new JdbcDataSource();
            source.setURL("jdbc:h2:mem:" + UUID.randomUUID());
            connection = source.getConnection();
            try (var sql = connection.createStatement()) {
                sql.execute("CREATE TABLE tc_forward_servers (id BIGINT PRIMARY KEY, type VARCHAR,"
                        + " active BOOLEAN, transmissionenabled BOOLEAN)");
                sql.execute("INSERT INTO tc_forward_servers VALUES (7,'SUTRAN_V2',TRUE,TRUE)");
                sql.execute("CREATE TABLE tc_positions (id BIGINT PRIMARY KEY, deviceid BIGINT)");
                sql.execute("INSERT INTO tc_positions VALUES (99,1)");
                sql.execute("CREATE TABLE tc_device_forward_server (id BIGINT PRIMARY KEY, deviceid BIGINT,"
                        + " serverid BIGINT, lastsent TIMESTAMP)");
                sql.execute("INSERT INTO tc_device_forward_server VALUES (1,1,7,NULL)");
                sql.execute("CREATE TABLE tc_forward_deliveries (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " positionid BIGINT, serverid BIGINT, status VARCHAR, payload VARCHAR, attempts INT,"
                        + " nextattempt TIMESTAMP, httpstatus INT, responsecode INT, crc VARCHAR, errormessage VARCHAR,"
                        + " createdtime TIMESTAMP, senttime TIMESTAMP, updatedtime TIMESTAMP)");
            }
            storage = new DatabaseStorage(new Config(), source, mapper) {
                @Override
                public <T> java.util.List<T> getObjects(Class<T> type, Request request) throws StorageException {
                    if (type == ForwardDelivery.class && request.getOrder() != null && failingRecoveryRead) {
                        throw new StorageException("Synthetic recovery read failure");
                    }
                    return super.getObjects(type, request);
                }
                @Override
                public <T> void updateObject(T entity, Request request) throws StorageException {
                    if (entity instanceof ForwardDelivery delivery && failingAttemptWrite
                            && delivery.getAttempts() > 0 && delivery.getStatus().equals("PROCESSING")) {
                        throw new StorageException("Synthetic attempt write failure");
                    }
                    if (entity instanceof ForwardDelivery delivery && delivery.getStatus().equals(failingStatus)) {
                        throw new StorageException("Synthetic write failure");
                    }
                    super.updateObject(entity, request);
                }
            };
            server.setId(7);
        }

        ForwardDelivery delivery() throws Exception {
            return storage.getObjects(ForwardDelivery.class, new Request(new Columns.All())).get(0);
        }

        @Override
        public void close() throws Exception {
            connection.close();
        }
    }

    @Test
    void lostCallbackAndFailedAcknowledgementWriteAreNeverResentAfterRestart() throws Exception {
        for (boolean callbackReceived : new boolean[] {false, true}) {
            try (var f = new Fixture()) {
                f.failingStatus = ForwardDelivery.STATUS_DELIVERED;
                var requests = new AtomicInteger();
                var firstProcess = new SutranDeliveryQueue(f.storage, f.mapper, (server, request, callback) -> {
                    requests.incrementAndGet();
                    if (callbackReceived) {
                        callback.accept(success());
                    }
                });
                assertTrue(firstProcess.enqueue(f.server, positionData()));
                assertEquals(ForwardDelivery.STATUS_PROCESSING, f.delivery().getStatus());
                f.failingStatus = null;
                var restarted = new SutranDeliveryQueue(f.storage, f.mapper,
                        (server, request, callback) -> requests.incrementAndGet());
                restarted.recover();
                assertEquals(1, requests.get());
                assertEquals(ForwardDelivery.STATUS_FAILED, f.delivery().getStatus());
                assertEquals(ForwardDelivery.ERROR_ACKNOWLEDGEMENT_UNKNOWN, f.delivery().getErrorMessage());
                assertNull(f.delivery().getCrc());
                assertNull(f.delivery().getSentTime());
                assertEquals(1, f.delivery().getAttempts());
                try (var sql = f.connection.createStatement();
                        var rows = sql.executeQuery("SELECT lastsent FROM tc_device_forward_server")) {
                    assertTrue(rows.next());
                    assertNull(rows.getTimestamp(1), "No activity without a durable acknowledgement");
                }
            }
        }
    }

    @Test
    void newerPositionCannotOvertakeAnUnsentPreflightFailure() throws Exception {
        try (var f = new Fixture()) {
            var calls = new java.util.ArrayList<String>();
            var queue = new SutranDeliveryQueue(f.storage, f.mapper, (server, request, beforeAttempt, callback) -> {
                if (beforeAttempt.test(1)) {
                    calls.add(request.getTimeDevice());
                    callback.accept(success());
                } else {
                    callback.accept(new SutranSendResult(new SutranDeliveryResult(
                            SutranDeliveryResult.Status.RETRY, 0, null, null, "Synthetic preflight failure"), 0));
                }
            }, true, null, Runnable::run);
            f.failingAttemptWrite = true;
            queue.enqueue(f.server, positionData());
            f.failingAttemptWrite = false;
            var newer = positionData();
            newer.getPosition().setId(100);
            newer.getPosition().setFixTime(Date.from(Instant.parse("2026-08-28T12:00:40Z")));
            queue.enqueue(f.server, newer);
            assertTrue(calls.isEmpty(), "Newer position must wait for the unsent predecessor");
            queue.recover();
            assertEquals(java.util.List.of("2026-08-28 07:00:00", "2026-08-28 07:00:40"), calls);
        }
    }

    @Test
    void firstAttemptWriteFailureRemainsPendingAndResumesWithoutLostWork() throws Exception {
        verifyFirstAttemptWriteFailure(false);
        verifyFirstAttemptWriteFailure(true);
    }

    private void verifyFirstAttemptWriteFailure(boolean pendingResetAlsoFails) throws Exception {
        try (var f = new Fixture()) {
            var requests = new AtomicInteger();
            var queue = new SutranDeliveryQueue(f.storage, f.mapper, (server, request, beforeAttempt, callback) -> {
                if (beforeAttempt.test(1)) {
                    requests.incrementAndGet();
                    callback.accept(success());
                } else {
                    callback.accept(new SutranSendResult(new SutranDeliveryResult(
                            SutranDeliveryResult.Status.RETRY, 0, null, null, "Synthetic preflight failure"), 0));
                }
            }, true, null, Runnable::run);
            f.failingStatus = pendingResetAlsoFails ? ForwardDelivery.STATUS_PENDING : null;
            f.failingAttemptWrite = true;
            queue.enqueue(f.server, positionData());
            assertEquals(0, requests.get());
            assertEquals(0, f.delivery().getAttempts());
            assertEquals(pendingResetAlsoFails ? ForwardDelivery.STATUS_PROCESSING : ForwardDelivery.STATUS_PENDING,
                    f.delivery().getStatus());
            f.failingAttemptWrite = false;
            f.failingStatus = null;
            queue.recover();
            assertEquals(1, requests.get());
            assertEquals(1, f.delivery().getAttempts());
            assertEquals(ForwardDelivery.STATUS_DELIVERED, f.delivery().getStatus());
        }
    }

    @Test
    void repeatedRecoveryDoesNotQuarantineOrDuplicateLiveWork() throws Exception {
        try (var f = new Fixture()) {
            var calls = new AtomicInteger();
            var callback = new java.util.concurrent.atomic.AtomicReference<
                    java.util.function.Consumer<SutranSendResult>>();
            var queue = new SutranDeliveryQueue(f.storage, f.mapper, (server, request, handler) -> {
                calls.incrementAndGet();
                callback.set(handler);
            });
            queue.enqueue(f.server, positionData());
            queue.recover();
            queue.recover();
            assertEquals(1, calls.get());
            assertEquals(ForwardDelivery.STATUS_PROCESSING, f.delivery().getStatus());
            callback.get().accept(success());
            queue.recover();
            assertEquals(1, calls.get());
            assertEquals(ForwardDelivery.STATUS_DELIVERED, f.delivery().getStatus());
        }
    }

    @Test
    void failedAcknowledgementMustNotPublishLastSent() throws Exception {
        try (var f = new Fixture()) {
            f.failingStatus = ForwardDelivery.STATUS_DELIVERED;
            new SutranDeliveryQueue(f.storage, f.mapper,
                    (server, request, callback) -> callback.accept(success())).enqueue(f.server, positionData());
            try (var sql = f.connection.createStatement();
                    var rows = sql.executeQuery("SELECT lastsent FROM tc_device_forward_server")) {
                assertTrue(rows.next());
                assertNull(rows.getTimestamp(1));
            }
        }
    }

    @Test
    void recoveryCanResumeAfterDatabaseReadFailure() throws Exception {
        try (var f = new Fixture()) {
            f.failingStatus = ForwardDelivery.STATUS_PROCESSING;
            new SutranDeliveryQueue(f.storage, f.mapper, (server, request, callback) -> fail("No HTTP"))
                    .enqueue(f.server, positionData());
            f.failingStatus = null;
            var calls = new AtomicInteger();
            var scheduled = new java.util.concurrent.atomic.AtomicReference<Runnable>();
            var scheduler = org.mockito.Mockito.mock(java.util.concurrent.ScheduledExecutorService.class);
            org.mockito.Mockito.doAnswer(invocation -> {
                scheduled.set(invocation.getArgument(0));
                return null;
            }).when(scheduler).schedule(org.mockito.ArgumentMatchers.any(Runnable.class),
                    org.mockito.ArgumentMatchers.eq(30L),
                    org.mockito.ArgumentMatchers.eq(java.util.concurrent.TimeUnit.SECONDS));
            var queue = new SutranDeliveryQueue(f.storage, f.mapper, (server, request, beforeAttempt, callback) -> {
                if (beforeAttempt.test(1)) {
                    calls.incrementAndGet();
                    callback.accept(success());
                }
            }, true, scheduler, Runnable::run);
            f.failingRecoveryRead = true;
            queue.recover();
            assertNotNull(scheduled.get(), "Failed recovery must schedule another sweep");
            f.failingRecoveryRead = false;
            scheduled.get().run();
            assertEquals(1, calls.get());
            assertEquals(ForwardDelivery.STATUS_DELIVERED, f.delivery().getStatus());
        }
    }

    @Test
    void failedInFlightWriteLeavesPendingWithoutHttpAndCanResume() throws Exception {
        try (var f = new Fixture()) {
            f.failingStatus = ForwardDelivery.STATUS_PROCESSING;
            var requests = new AtomicInteger();
            SutranDeliveryQueue.Sender sender = (server, request, callback) -> {
                requests.incrementAndGet();
                callback.accept(success());
            };
            new SutranDeliveryQueue(f.storage, f.mapper, sender).enqueue(f.server, positionData());
            assertEquals(0, requests.get());
            assertEquals(ForwardDelivery.STATUS_PENDING, f.delivery().getStatus());
            f.failingStatus = null;
            new SutranDeliveryQueue(f.storage, f.mapper, sender).recover();
            assertEquals(1, requests.get());
            assertEquals(ForwardDelivery.STATUS_DELIVERED, f.delivery().getStatus());
            assertEquals("S8J7e", f.delivery().getCrc());
        }
    }

    private static SutranSendResult success() {
        return new SutranSendResult(new SutranDeliveryResult(
                SutranDeliveryResult.Status.DELIVERED, 200, 2001, "S8J7e", null), 1);
    }

    private static PositionData positionData() {
        var device = new Device();
        device.setName("ABC123");
        var position = new Position();
        position.setId(99);
        position.setValid(true);
        position.setLatitude(-11.4);
        position.setLongitude(-76.9);
        position.setFixTime(Date.from(Instant.parse("2026-08-28T12:00:00Z")));
        var result = new PositionData();
        result.setDevice(device);
        result.setPosition(position);
        return result;
    }
}
