package org.traccar.forward.sutran;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.HttpServer;
import jakarta.ws.rs.client.ClientBuilder;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.postgresql.ds.PGSimpleDataSource;
import org.traccar.config.Config;
import org.traccar.forward.PositionData;
import org.traccar.model.Device;
import org.traccar.model.ForwardDelivery;
import org.traccar.model.ForwardServer;
import org.traccar.model.Position;
import org.traccar.storage.DatabaseStorage;
import org.traccar.storage.query.Columns;
import org.traccar.storage.query.Request;

import java.net.InetSocketAddress;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Date;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.*;

/** Only a marked, disposable PostgreSQL cluster and a loopback HTTP receiver are allowed. */
@EnabledIfEnvironmentVariable(named = "TRACCAR_TEST_PG_URL",
        matches = "jdbc:postgresql://127\\.0\\.0\\.1:[0-9]+/geofence_validation")
class SutranPostgresRehearsalTest {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private com.zaxxer.hikari.HikariDataSource isolatedSource() throws Exception {
        var source = new PGSimpleDataSource();
        source.setURL(System.getenv("TRACCAR_TEST_PG_URL"));
        source.setUser("validation_owner");
        source.setConnectTimeout(5);
        source.setSocketTimeout(10);
        String schema = "sutran_runtime_" + UUID.randomUUID().toString().replace("-", "");
        try (var connection = source.getConnection(); var sql = connection.createStatement()) {
            try (var rows = sql.executeQuery(
                    "SELECT current_database(),current_setting('traccar.validation_cluster',true)")) {
                assertTrue(rows.next());
                assertEquals("geofence_validation", rows.getString(1));
                var marker = System.getenv("TRACCAR_TEST_PG_TOKEN");
                assertNotNull(marker);
                assertFalse(marker.isBlank());
                assertEquals(marker, rows.getString(2), "Refusing an unmarked cluster");
            }
            sql.execute("CREATE SCHEMA " + schema);
        }
        source.setCurrentSchema(schema);
        try (var connection = source.getConnection(); var sql = connection.createStatement()) {
            sql.execute("CREATE TABLE tc_forward_servers (id BIGINT PRIMARY KEY,type VARCHAR(32),"
                    + " active BOOLEAN,transmissionenabled BOOLEAN)");
            sql.execute("INSERT INTO tc_forward_servers VALUES (7,'SUTRAN_V2',TRUE,TRUE)");
            sql.execute("CREATE TABLE tc_positions (id BIGINT PRIMARY KEY,deviceid BIGINT)");
            sql.execute("CREATE TABLE tc_device_forward_server (id BIGINT PRIMARY KEY,deviceid BIGINT,"
                    + " serverid BIGINT,lastsent TIMESTAMP)");
            sql.execute("CREATE TABLE tc_forward_deliveries (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " positionid BIGINT,serverid BIGINT,status VARCHAR(16),payload TEXT,attempts INT,"
                    + " nextattempt TIMESTAMP,httpstatus INT,responsecode INT,crc TEXT,errormessage VARCHAR(512),"
                    + " createdtime TIMESTAMP,senttime TIMESTAMP,updatedtime TIMESTAMP,UNIQUE(positionid,serverid))");
            for (int device = 1; device <= 8; device++) {
                sql.execute("INSERT INTO tc_device_forward_server VALUES (" + device + "," + device + ",7,NULL)");
            }
        }
        var pool = new com.zaxxer.hikari.HikariConfig();
        pool.setDataSource(source);
        pool.setMaximumPoolSize(8);
        pool.setConnectionTimeout(10000);
        return new com.zaxxer.hikari.HikariDataSource(pool);
    }

    @Test
    void abruptJvmExitAfterRemoteAcceptanceIsQuarantinedOnRestart() throws Exception {
        String classpathFile = System.getProperty("sutran.test.classpathFile");
        org.junit.jupiter.api.Assumptions.assumeTrue(classpathFile != null, "Use the SUTRAN validation init script");
        String classpath = Files.readString(Path.of(classpathFile));
        try (var source = isolatedSource()) {
            var requests = new AtomicInteger();
            var receiver = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
            receiver.createContext("/transmisiones", exchange -> {
                exchange.getRequestBody().readAllBytes();
                requests.incrementAndGet();
                byte[] response = "{\"code\":2001,\"crc\":\"S8J7e\"}".getBytes(StandardCharsets.UTF_8);
                exchange.sendResponseHeaders(200, response.length);
                exchange.getResponseBody().write(response);
                exchange.close();
            });
            receiver.start();
            Process child = null;
            try {
                Files.createDirectories(Path.of("build/reports"));
                Path arguments = Path.of("build/reports/sutran-crash-probe.args");
                Files.writeString(arguments, "-cp\n\"" + classpath.replace('\\', '/') + "\"\n"
                        + SutranCrashProbe.class.getName() + "\n"
                        + ((PGSimpleDataSource) source.getDataSource()).getCurrentSchema() + "\n"
                        + "http://127.0.0.1:" + receiver.getAddress().getPort() + "/transmisiones\n");
                child = new ProcessBuilder(Path.of(System.getProperty("java.home"), "bin", "java").toString(),
                        "@" + arguments.toAbsolutePath())
                        .redirectErrorStream(true)
                        .redirectOutput(Path.of("build/reports/sutran-crash-probe.log").toFile()).start();
                assertTrue(child.waitFor(30, TimeUnit.SECONDS));
                assertEquals(73, child.exitValue(), "Child must exit at the simulated crash point");
                assertEquals(1, requests.get());
                var storage = new DatabaseStorage(new Config(), source, MAPPER);
                var before = storage.getObjects(ForwardDelivery.class, new Request(new Columns.All())).get(0);
                assertEquals("PROCESSING", before.getStatus());
                assertEquals(1, before.getAttempts());
                assertNull(before.getCrc());
                var queue = new SutranDeliveryQueue(storage, MAPPER,
                        (server, request, callback) -> fail("An uncertain frame must never be resent"));
                queue.recover();
                var after = storage.getObjects(ForwardDelivery.class, new Request(new Columns.All())).get(0);
                assertEquals("FAILED", after.getStatus());
                assertEquals(ForwardDelivery.ERROR_ACKNOWLEDGEMENT_UNKNOWN, after.getErrorMessage());
                assertEquals(1, after.getAttempts());
                assertEquals(1, requests.get());
            } finally {
                if (child != null && child.isAlive()) {
                    child.destroyForcibly(); // Only the child created by this test.
                    child.waitFor(10, TimeUnit.SECONDS);
                }
                receiver.stop(0);
            }
        }
    }

    @Test
    void restartBacklogAndEightVehiclesEveryFortySeconds() throws Exception {
        var source = isolatedSource();
        var storage = new DatabaseStorage(new Config(), source, MAPPER);
        var scheduler = Executors.newScheduledThreadPool(2);
        var workers = Executors.newFixedThreadPool(8);
        var receiverWorkers = Executors.newFixedThreadPool(8);
        var receiver = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
        receiver.setExecutor(receiverWorkers);
        var observed = new ConcurrentHashMap<String, AtomicInteger>();
        var accepted = new ConcurrentHashMap<String, String>();
        var lastTime = new ConcurrentHashMap<String, String>();
        var violations = new java.util.concurrent.ConcurrentLinkedQueue<String>();
        var requests = new AtomicInteger();
        receiver.createContext("/transmisiones", exchange -> {
            try {
                var body = MAPPER.readTree(exchange.getRequestBody());
                String plate = body.get("plate").asText();
                String time = body.get("time_device").asText();
                String key = plate + "/" + time;
                int call = observed.computeIfAbsent(key, unused -> new AtomicInteger()).incrementAndGet();
                requests.incrementAndGet();
                boolean transientFailure = plate.equals("SIM001") && call == 1;
                int status = transientFailure ? 503 : 200;
                if (!transientFailure) {
                    if (accepted.putIfAbsent(key, time) != null) {
                        violations.add("Duplicate accepted frame");
                    }
                    lastTime.compute(plate, (unused, previous) -> {
                        if (previous != null && time.compareTo(previous) < 0) {
                            violations.add("Out of order frame");
                        }
                        return time;
                    });
                }
                byte[] response = (transientFailure ? "Unavailable"
                        : "{\"code\":2001,\"crc\":\"S8J7e\",\"result\":\"OK\"}")
                        .getBytes(StandardCharsets.UTF_8);
                exchange.sendResponseHeaders(status, response.length);
                exchange.getResponseBody().write(response);
            } finally {
                exchange.close();
            }
        });
        receiver.start();
        long started = System.nanoTime();
        try (var http = ClientBuilder.newClient()) {
            var client = new SutranClient(http, MAPPER, scheduler, new SutranPayloadMapper(),
                    URI.create("http://127.0.0.1:" + receiver.getAddress().getPort() + "/transmisiones"),
                    UUID.randomUUID().toString(), 2000, 3000, 3, 10, 100);
            SutranDeliveryQueue.TrackedSender sender = (server, request, beforeAttempt, callback) ->
                    client.sendTracked(request, beforeAttempt, callback);
            var destination = new ForwardServer();
            destination.setId(7);

            // One hour of backlog: 8 vehicles * 90 reports. Seeded, never sent before recovery.
            for (int cycle = 0; cycle < 90; cycle++) {
                for (int device = 1; device <= 8; device++) {
                    var data = data(cycle, device);
                    var delivery = new ForwardDelivery();
                    delivery.setPositionId(data.getPosition().getId());
                    delivery.setServerId(7);
                    delivery.setStatus(ForwardDelivery.STATUS_PENDING);
                    delivery.setPayload(MAPPER.writeValueAsString(new SutranPayloadMapper().map(data)));
                    delivery.setCreatedTime(new Date());
                    delivery.setUpdatedTime(new Date());
                    storage.addObject(delivery, new Request(new Columns.Exclude("id")));
                    insertPosition(source, data);
                }
            }
            // Simulated old process: preserve its eight uncertain requests without sending them.
            try (var connection = source.getConnection(); var sql = connection.createStatement()) {
                sql.execute("INSERT INTO tc_forward_deliveries(positionid,serverid,status,payload,attempts)"
                        + " SELECT 10000+n,7,'PROCESSING','{}',2 FROM generate_series(1,8) n");
            }
            var queue = new SutranDeliveryQueue(storage, MAPPER, sender, true, scheduler, workers);
            long recoveryStarted = System.nanoTime();
            queue.recover();
            awaitDelivered(source, 720, 120);
            long backlogMillis = TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - recoveryStarted);

            // Actual wall-clock interval, including repeated background recovery sweeps.
            long liveStart = System.nanoTime();
            var enqueueMillis = new java.util.ArrayList<Long>();
            for (int round = 0; round < 3; round++) {
                long deadline = liveStart + TimeUnit.SECONDS.toNanos(40L * round);
                long remaining = deadline - System.nanoTime();
                if (remaining > 0) {
                    TimeUnit.NANOSECONDS.sleep(remaining);
                }
                long burstStart = System.nanoTime();
                for (int device = 1; device <= 8; device++) {
                    var data = data(90 + round, device);
                    insertPosition(source, data);
                    assertTrue(queue.enqueue(destination, data));
                }
                enqueueMillis.add(TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - burstStart));
                awaitDelivered(source, 720 + (round + 1) * 8, 30);
            }
            assertTrue(violations.isEmpty(), violations.toString());
            assertEquals(744, accepted.size());
            assertEquals(837, requests.get()); // 744 frames plus 93 controlled retries for SIM001.
            try (var connection = source.getConnection(); var sql = connection.createStatement()) {
                try (var rows = sql.executeQuery("SELECT count(*),sum(attempts) FROM tc_forward_deliveries"
                        + " WHERE status='DELIVERED' AND crc='S8J7e' AND senttime IS NOT NULL"
                        + " AND errormessage IS NULL")) {
                    assertTrue(rows.next());
                    assertEquals(744, rows.getInt(1));
                    assertEquals(837, rows.getInt(2));
                }
                try (var rows = sql.executeQuery("SELECT count(*) FROM tc_forward_deliveries WHERE status='FAILED'"
                        + " AND errormessage='SUTRAN_ACKNOWLEDGEMENT_UNKNOWN' AND attempts=2")) {
                    assertTrue(rows.next());
                    assertEquals(8, rows.getInt(1));
                }
                try (var rows = sql.executeQuery("SELECT count(*) FROM tc_device_forward_server WHERE lastsent IS NOT NULL")) {
                    assertTrue(rows.next());
                    assertEquals(8, rows.getInt(1));
                }
            }
            var report = Map.of("vehicles", 8, "intervalSeconds", 40, "destinations", 1,
                    "backlogFrames", 720, "delivered", 744, "httpRequests", requests.get(),
                    "uncertainNotResent", 8, "backlogRecoveryMillis", backlogMillis,
                    "burstEnqueueMillis", enqueueMillis,
                    "totalMillis", TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - started));
            Files.createDirectories(Path.of("build/reports"));
            MAPPER.writerWithDefaultPrettyPrinter().writeValue(
                    Path.of("build/reports/sutran-postgres-runtime.json").toFile(), report);
        } finally {
            scheduler.shutdownNow();
            workers.shutdownNow();
            receiver.stop(0);
            receiverWorkers.shutdownNow();
            assertTrue(workers.awaitTermination(10, TimeUnit.SECONDS));
            source.close();
        }
    }

    private static void awaitDelivered(javax.sql.DataSource source, int expected, int seconds) throws Exception {
        long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(seconds);
        while (System.nanoTime() < deadline) {
            try (var connection = source.getConnection(); var sql = connection.createStatement();
                    var rows = sql.executeQuery("SELECT count(*) FROM tc_forward_deliveries WHERE status='DELIVERED'")) {
                rows.next();
                if (rows.getInt(1) == expected) {
                    return;
                }
            }
            Thread.sleep(100);
        }
        fail("The isolated queue did not drain within " + seconds + " seconds");
    }

    private static PositionData data(int cycle, int deviceId) {
        var device = new Device();
        device.setId(deviceId);
        device.setName(String.format("SIM%03d", deviceId));
        var position = new Position();
        position.setId(cycle * 8L + deviceId);
        position.setDeviceId(deviceId);
        position.setValid(true);
        position.setLatitude(-11.4);
        position.setLongitude(-76.9);
        position.setFixTime(Date.from(Instant.parse("2026-09-01T12:00:00Z").plusSeconds(cycle * 40L)));
        var data = new PositionData();
        data.setDevice(device);
        data.setPosition(position);
        return data;
    }

    private static void insertPosition(javax.sql.DataSource source, PositionData data) throws Exception {
        try (var connection = source.getConnection(); var sql = connection.prepareStatement(
                "INSERT INTO tc_positions VALUES (?,?)")) {
            sql.setLong(1, data.getPosition().getId());
            sql.setLong(2, data.getDevice().getId());
            sql.executeUpdate();
        }
    }
}
